module.exports.HMOList = [
  "Doc Hudson",
  "Megamind",
  "HuHot Guy",
  "Mummy Pig",
  "Pingu",
  "King Juliean",
  "Wall-E",
  "Bob the Tomato",
  "Larry the Cucumber",
  "String Theory",
  "Beetlejuice",
  "Betelgeuse",
  "🫃",
  "Larry Ellison",
  "Undercover Mater",
  "Ur Mom",
  "Lord Farquad",
  "Principle Skinner",
  "Tinky Winky",
  "Subway Surfers Cop",
  "Clippy",
  ":O",
  "Burger King",
  "Wendy",
  "Big the Cat",
  "Ronald McDonald",
  "Margret Thatcher",
  "Jeffrey Epstein (I can fix him)",
  "8",
  "Plastic Dinosaur",
  "Just Dance Silhouette",
  "backyardigans penguin",
  "zoboomafoo",
  "Chris Kratt",
  "🦧",
  "William Howard Taft",
  "Alfred Nobel",
  "Northern Lion",
  "Agent 47",
  "Abomasnow",
  "Default Woman Mii",
  "The Shower Drain",
  "Robbin Willams from the hit movie flubber",
  "Flubber from the hit movie Robbin Willams",
  "Alf",
  "Tootsie Roll with a razor in it",
  "*",
  "<@1393814433473757255>",
  "Wumpus",
  "Among Us bobby",
  "Lego BatMan",
  "REV ROBOTICS©: SparkMax",
  "Hole in wall",
  "The concept of having a secure future",
  "Glorbo",
  "Sharktales Blueray DVD",
  "gravity",
  "blue",
  "github cat dude",
  "thanxgiving turkey",
  "Grunkle Stan",
  "Rocktopus",
  "NOT OPAMA",
  "Paper Crane folded from grandma's will",
  "page 23 of the Great Gatsby",
  "The mongolian subtitles of Stranger Things",
  "Orange Crayon",
  "Jaxson",
  "Eleanor Roosevelt",
  "Victreebel",
  "Mushroom Man from hollowknight",
  "<@683070525710532608> What that mouth doooo",
  "Steam Down Guy",
  "Tomato Soup",
  "King K Rool",
  "Minecraft Jenny Mod",
  "Jared From Subway",
  "Jimbo from Balatro",
  "Quincy From BTD6",
  "Papyrus' left leg",
  "Einstien's brain in a jar",
  "Pufferfish king grimm",
  "{",
  "the rizzler with old man filter on",
  "Hawk Tuah's wisdom teeth",
  "The drippy Pope",
  "Scoutmaster Myers",
  "Pig Ganon",
  "Phoenix Tuner X",
  "Johnny Test werewolf",
  "John Philip Sousa",
  "Horse Corpse",
  "Jack from the hit story jack and jill",
  "Wolf (grandma alt)",
  "Boo from Monsters inc (movie was made in 2001 so its ok now) - The Twink gave me the ok",
  "God",
  "Egyptian god Rah",
];
